export const sanctuarydata = {
	overview: "Sanctuary is an important aspect of your progression. The bulidings allow you to generate all sorts of important resources (Penguins, Phantasma, Molagora, Skystones, Ancient Coins, and Conquest Points) and craft Equipments and Catalysts necessary for you to speed up progression. Which is why it is important to quickly obtain all the Breath of Orbis that are scattered all over the Adventure maps. There will be one Breath of Orbis in each stage of the map (a total of 12 breath of orbis) with an icon hovering over the stage to indicate that a Breath of Orbis can be obtain.",
	overview2: "If you include 12 from adventure Ritania, 12 from the Unrecorded History, and 2 from the Cidonia AP shop (Stage 1 and 3), then you have a total of 26 Breath of Orbis to use. Because it is impossible to fully upgrade every single workshop, players have to prioritize on what they want to upgrade unless they are willing to spend a large sum of gold resetting upgrades (not really ideal for a new player to spend that much gold).",
	priority: "When you start playing, it is your best interest to collect all the Breath of Orbis as soon as possible since the buildings in the Sanctuary are valuable throughout your progression. This section of the guide is mainly to recommend priority on what to upgrade initially with your Breath of Orbis.",
	forestofsoul: "Upgrading Forest of Souls, Soul Isle Extension, to Level 3 should be the first thing you should spend with your Breath of Orbis. Increasing the slot to nuture creatures from 1 slot to 3 slots will speed up the time it takes for you to make Phantasma which means you will 6 star your units at a faster rate.",
	highcommand: "The next thing you should upgrade should be the High Command. I suggest only upgrading each part of the building to Level 1. This will allow you to dispatch two missions for 10 Conquest Points and 10 Ancient Coins for a total of 2 Energy every 2 hours. Earning Conquest points at a consistent rate allows you to obtain Item Level 88 arena gear as soon as possible (A big boost to your gear progression). A constant supply of Ancient Coins allows you to purchase Accessory Charms which are going to be the main source of experience when it comes to enhancing your accessory equipments.",
	lowpriority: "Although this section is about low priority upgrades, it does not mean that it is unnecessary. I place these upgrades on a lower priority because as a new player these are not as important. As you progress further, these upgrades will become more and more important.",
	steelworkshop: "Once you have progress far enough in your Hunts (I say around stage 8 to 11 depending on how much you are struggling in terms of gear.), the Steel Workshop should be fully upgraded. The Steel Workshop is the most important building in regards to late game. Epic Seven is mostly just a gear grind and it should be your best interest to fully upgrade the building to take advantage of its gear crafting system (Reducing cost to craft and increasing chance of crafting an Epic/Heroic Equipment).",
	steeple: "Alchemist's Steeple is one of the newest addition in the Sanctuary. The ability to craft normal and epic catalyst makes it relatively easy for player to fully awaken their heroes. Fully awakening heroes are not necessary for new players as the amount of resources to craft can be quite costly. It is however very useful once get pretty far into the game. I would at least upgrade Laboratory and Ingredient Storage to Level 3 once you gotten to the point where u feel like you can afford the resource cost of crafting catalysts.",
	heartoforbis: "Heart of Orbis is a building where upgrading is based on personal preference. I do suggest fully upgrading Mirror of Light and Benedictory Sanctum to maximize the amount of skystone you earn. You can upgrade Cradle of Life based on how often you play the game. (I have my Cradle of Life at Level 2)",
	note1: "something about what is your end result with buildings.",
	note2: "The remaining Breath of Orbis should used based on your own personal preference. After upgrading all the priorities, there are really no wrong upgrades."
}